### ISSUE TITLE
Local InfluxDB

### ISSUE THREAD

**Issue by nickvsnetworking** [P1sec/QCSuper#112]
G'day team,

Finally got some time to play with this, but I can't seem to get the local InfluxDB connection to come up on the Debug or Release builds.

IIRC in the talk at OSMNC you mentioned logging Influx data to a file and the importing it - Is this this functionality?

I did a bit of debugging and it looks like when you tap "Setup Local DB" it tries to connect to an InfluxDB server running on localhost, but I can't find much online about running an InfluxDB server on Android, are you able to give me a point in the right direction here?

My use case is logging data on the phone and then uploading to InfluxDB when we have connectivity again, so pushing directly in Influx Cloud isn't an option.

![image](https://github.com/P1sec/QCSuper/assets/26107392/295df05f-2bde-41d4-ad3e-efaa57a91a11)

**Comment by p1-mmr** [comment]
Hello,

I don't really know what OSMNC or OMNT is, and am not an InfluxDB user, it's likely opened at the wrong place I would be curious which tool this issue is about? (:

**Comment by nickvsnetworking** [comment]
Ha! Apologies guys, I opened this on the wrong repo, was playing with both at the same time!
[OMNT is the OpenMobileNetworkToolkit](https://github.com/omnt/OpenMobileNetworkToolkit)
