### ISSUE TITLE
Feature Request: Send pcap data to stdout

### ISSUE THREAD

**Issue by eriksejr** [P1sec/QCSuper#14]
If I could make a minor feature request. It would be useful to be able to send the pcap data directly to standard output, allowing the launch of the script via SSH and tunnelling of the data to wireshark on a remote host.

**Comment by p1-mmr** [comment]
Hello,

Thanks for this request, this has just been implemented in commit 78a46395971373aff0868c89fc0af82a176ae67e.

You may want to specify `-` for arguments that take a file to have it signify either stdin or stdout. You should also be able to use the regular `/dev/stdin` and `/dev/stdout`, if you prefer.

When doing so, if you pass a file compressed with GZip or another format, you should also not forget to uncompress it first.

Regards,

**Comment by eriksejr** [comment]
Thanks again!
