### ISSUE TITLE
Ioctl Invalid argument

### ISSUE THREAD

**Issue by darox** [P1sec/QCSuper#47]
Thank you for creating this nice tool. 

I have a OnePlus 8 Pro which exposes the diag port but when I start the program is report an error:

```
oot@xps:/home/dario/dev/radio/QCSuper-master# ./qcsuper.py --adb --wireshark-live
ioctl: Invalid argument

The connection to the adb bridge was closed, or preempted by another QCSuper instance
```

**Comment by Subangkar** [comment]
How did this get resolved? I'm facing the same.
