### ISSUE TITLE
Connectivity fails with Sony Xperia Z3 (D5803)

### ISSUE THREAD

**Issue by Lofmir** [P1sec/QCSuper#5]
I'm currently struggling with connecting the Sony Xperia Z3 (D5803). Do you support this device? I get the output from the tool: 
`# ./qcsuper.py --adb --wireshark-live`
`Could not find /dev/diag, does your phone have a Qualcomm chip?`

**Comment by p1-mmr** [comment]
Hello,

Could you please share the output of the following commands: `adb shell ls /dev; adb shell ls /` ?

**Comment by Lofmir** [comment]
# adb shell ls /dev; adb shell ls /
opendir failed, Permission denied
acct
cache
charger
config
crashtag
d
data
default.prop
dev
etc
file_contexts
firmware
fstab.qcom
init
init.class_main.sh
init.environ.rc
init.mdm.sh
init.qcom.class_core.sh
init.qcom.early_boot.sh
init.qcom.factory.sh
init.qcom.rc
init.qcom.sh
init.qcom.ssr.sh
init.rc
init.sony-device-common.rc
init.sony-device.rc
init.sony-platform.rc
init.sony.rc
init.sony.usb.rc
init.target.rc
init.trace.rc
init.usb.rc
init.usbmode.sh
init.zygote32.rc
logo.rle
lta-label
mnt
proc
property_contexts
res
root
sbin
sdcard
sdcard1
seapp_contexts
selinux_version
sepolicy
service_contexts
storage
sys
system
tmp
tmp-mksh
tombstones
ueventd.qcom.rc
ueventd.rc
usbdisk
vendor

**Comment by p1-mmr** [comment]
Hello, I think that I may have fixed the issue in 9f419d861aa27cd3ac0d9dad6250fc8aae7faf1c. Can you pull the latest commits and confirm?

**Comment by Lofmir** [comment]
The latest commit works now for me! :-) THX 👍
