### ISSUE TITLE
QC Super ...

### ISSUE THREAD

**Issue by yfinality** [P1sec/QCSuper#69]
Hello.
1. How will it be used 24/7 80% with one BTS. For example, the headquarters will not pay attention to him after a year?
2. One USB for ROTER AND PHONE?
3. What is the final cost along with the shipment (if it is to be delivered to Poland)?
I'm waiting for your reply.

**Comment by p1-mmr** [comment]
Hello!

This is not a tool for intercepting communications. This is a baseband debugging tool intended for technicians, allowing to analyze the communications sent by your own phone or device.

This is also not something physical that can be bought or delivered. That is just software that can be download for free from Github.

Regards,
