### ISSUE TITLE
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C

### ISSUE THREAD

**Issue by sprout42** [P1sec/QCSuper#7]
I tried this on a rooted Nexus5x with a data-only googlefi sim and wasn't able to see any messages in wireshark (I wasn't sure if it would work but figured it was worth a try).

I did see the following errors on the command line:
```
$ ./qcsuper.py --adb --wireshark-live

[+] Enabled logging for: 1X (1), WCDMA (4), GSM (5), UMTS (7), DTV (10), APPS/LTE/WIMAX (11), TDSCDMA (13)

Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
Unknown log type received for LOG_LTE_RRC_OTA_MSG_LOG_C: 11
...
```

**Comment by p1-mmr** [comment]
Hello,

This is rather interesting, could you run QCSuper with this option:

```
./qcsuper.py --adb --dlf-dump /tmp/output_file.dlf
```

Optionally generate a few cell traffic, wait a few minutes and upload the raw `.dlf` file to this issue? (or send it aｔ mmr at p1sec ｄｏｔ com)

This would help us troubleshooting. Thanks!

**Comment by eriksejr** [comment]
Hi there,
Thanks for your work on this. I have tried this on a Qualcomm based sierra wireless MC7455 module, which exposes the debug port on /dev/ttyUSB0. I got the exact same messages as the OP and an empty pcap file.

I tried to dump the raw data to the .dlf as suggested, but the python script crashes after a few seconds:

```
./qcsuper.py --usb-modem /dev/ttyUSB0 --dlf-dump ./mc7455.dlf

[+] Enabled logging for: 1X (1), WCDMA (4), GSM (5), UMTS (7), DTV (10), APPS/LTE/WIMAX (11), TDSCDMA (13)

Warning: Wrong CRC: b'\x10\x00\xa4\x01\xa4\x01L\xb1\x0ez\xd5\x8d\xba\x04\x00\x00\x16sJ\xa6\x02\x00\x00\x00\xbe\xffw\x00\x00\x01\x0c\x00\x8b\x017\x00\x00\x00\xa6\xff\x8b\xff@\x00:\x01\x1d\x00\x08\x02\xbc\x00j\xff]\x00\x84\x10\x00\x1a\x00\x1a\x00\xa7\x18r[\x19\x8e\xba\x04\x00\x00\x01\x01\x00\x00\x00\x00(\x99\xc0\xac\x00\xb0\x04\x00' (is: 210, should be: e085)
Traceback (most recent call last):
  File "/home/pi/qcsuper/inputs/_base_input.py", line 156, in _read_thread
    self.read_loop()
  File "/home/pi/qcsuper/inputs/usb_modem.py", line 259, in read_loop
    self.dispatch_received_diag_packet(unframed_message)
  File "/home/pi/qcsuper/inputs/_base_input.py", line 351, in dispatch_received_diag_packet
    time() # Timestamp
  File "/home/pi/qcsuper/inputs/_base_input.py", line 383, in dispatch_diag_log
    module.on_log(log_type, log_payload, log_header, timestamp)
  File "/home/pi/qcsuper/modules/dlf_dump.py", line 25, in on_log
    assert unpack('<H', log_header[:2])[0] == len(log_header + log_payload)
AssertionError
```

**Comment by sprout42** [comment]
I was able to collect a log with no errors and sent it to @p1-mmr

**Comment by p1-mmr** [comment]
@sprout42 Hi. I think that I just fixed this in commit b09a4ab216fb6864c8bc8da8ef42419c6c02a5be.

**Comment by eriksejr** [comment]
Thanks for fixing this. It works for me now as well

**Comment by sprout42** [comment]
Yup, works for me as well.  Thanks!

**Comment by vitthal-agav** [comment]
> Hi there,
> Thanks for your work on this. I have tried this on a Qualcomm based sierra wireless MC7455 module, which exposes the debug port on /dev/ttyUSB0. I got the exact same messages as the OP and an empty pcap file.
> 
> I tried to dump the raw data to the .dlf as suggested, but the python script crashes after a few seconds:
> 
> ```
> ./qcsuper.py --usb-modem /dev/ttyUSB0 --dlf-dump ./mc7455.dlf
> 
> [+] Enabled logging for: 1X (1), WCDMA (4), GSM (5), UMTS (7), DTV (10), APPS/LTE/WIMAX (11), TDSCDMA (13)
> 
> Warning: Wrong CRC: b'\x10\x00\xa4\x01\xa4\x01L\xb1\x0ez\xd5\x8d\xba\x04\x00\x00\x16sJ\xa6\x02\x00\x00\x00\xbe\xffw\x00\x00\x01\x0c\x00\x8b\x017\x00\x00\x00\xa6\xff\x8b\xff@\x00:\x01\x1d\x00\x08\x02\xbc\x00j\xff]\x00\x84\x10\x00\x1a\x00\x1a\x00\xa7\x18r[\x19\x8e\xba\x04\x00\x00\x01\x01\x00\x00\x00\x00(\x99\xc0\xac\x00\xb0\x04\x00' (is: 210, should be: e085)
> Traceback (most recent call last):
>   File "/home/pi/qcsuper/inputs/_base_input.py", line 156, in _read_thread
>     self.read_loop()
>   File "/home/pi/qcsuper/inputs/usb_modem.py", line 259, in read_loop
>     self.dispatch_received_diag_packet(unframed_message)
>   File "/home/pi/qcsuper/inputs/_base_input.py", line 351, in dispatch_received_diag_packet
>     time() # Timestamp
>   File "/home/pi/qcsuper/inputs/_base_input.py", line 383, in dispatch_diag_log
>     module.on_log(log_type, log_payload, log_header, timestamp)
>   File "/home/pi/qcsuper/modules/dlf_dump.py", line 25, in on_log
>     assert unpack('<H', log_header[:2])[0] == len(log_header + log_payload)
> AssertionError
> ```
> 
> I will send you the dlf file generated before the crash

Hi guys,
I facing exactly same issue with same MC7455 sierra modem. can you please help me on this ?
Thanks in advance !

Vitthal
