### ISSUE TITLE
Could not find /dev/diag, does your phone have a Qualcomm chip?

### ISSUE THREAD

**Issue by ekagravarma10** [P1sec/QCSuper#72]
Hi @p1-martin ,
1. I am getting this error when trying for the following command :
         C:\Users\Administrator\Downloads\QCSuper-master\QCSuper-master>
         qcsuper.py --adb --wireshark-live
         **Could not find /dev/diag, does your phone have a Qualcomm chip?**
2. after above cmd I also tried **taro:/ # setprop sys.usb.config mtp** , it successfully ran but after this when I repeated the 1st process,
    it again showed the same error.
3. I have a qualcomm chipset .
4. The port(com17) is mentioned below .pls check the snippet 
![tempsnip](https://user-images.githubusercontent.com/105360844/167891595-5174e1c9-d8e5-4303-8c48-b2184f191224.png)

**Comment by p1-mmr** [comment]
Hello,

If your device indeed have a Qualcomm chipset, it may be fixed with recent QCSuper versions, see: 
https://github.com/P1sec/QCSuper/issues/91#issuecomment-1855709390
